### ISSUE TITLE
Want to be a part of kaggledevs.

### ISSUE THREAD

**Issue by ucalyptus** [kaggledevs/kaggledevs.github.io#1]
Hi @amitkumarj441 
Please see my Github.
Send me an invite to @ucalyptus or santaclaus30011998@gmail.com

**Comment by amitkumarj441** [comment]
Thanks @ucalyptus for the heads-up.

As you know that we've got a dedicated group of Kagglers on our telegram group and to become a member here on Github, we would consider your help to volunteer and be a part of this open group on Kaggledevs and especially on Kaggle itself.

If you're interested in volunteering for this open community of Kaggledevs, we would seek your help to design a simple website that directs Kaggle datasets and other external datasets which are open for research (or reproducible research). Not limited to datasets, but also research papers that are aligned for particular datasets.

P.S.: We'll give you the details of the data and papers once you've the design ready for the website. We're open to welcome volunteers like you to help get this group aboard and known to Data science community.

**Comment by ucalyptus** [comment]
@amitkumarj441  I would go ahead and create a design branch with the changes and a subsequent PR.

**Comment by ucalyptus** [comment]
Hi @amitkumarj441 check https://github.com/kaggledevs/kaggledevs.github.io/pull/2
